spring:
  redis:
    host: yim-redis
#    host: 192.168.163.133
server:
  port: 7006

zk:
  addr: yim-zookeeper:2181
  switch: true
  connect:
    timeout: 15000
  root: /ws-server

dubbo:
  application:
    logger: slf4j
