spring:
  redis:
    host: yim-redis
#    host: 192.168.163.133
server:
  port: 7006

zk:
  addr: yim-zookeeper:2181
  switch: true
  connect:
    timeout: 15000
  root: /ws-server

dubbo:
  application:
    logger: slf4j


#RocketMQ 配置
rocketmq:
  name-server: yim-rocketmq-nameserver:9876
  producer:
    group: Producer_Group_Failed_Msg
