package com.mvbbb.yim.common.protoc.enums;

public enum CtrlRequestType {
    GROUP_CREATE,GROUP_MEMBER_ADD,GROUP_JOIN,GROUP_EXIT,GROUP_DISSOLUTION,GROUP_LIST,GROUP_MEMBER_KICKOUT,
    FRIEND_ADD,FRIEND_DELETE,FRIEND_LIST,
    USER_INFO_GET,GROUP_INFO_GET,
    USER_NAME_UPDATE,USER_AVATAR_UPDATE;
}
